#!/bin/bash

# bash_profile

# http://stackoverflow.com/questions/3446320/in-vim-how-to-map-save-to-ctrl-s
stty -ixon

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
  declare -a files=(
  $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
  $HOME/.dotfiles/shell/bash_options # Options
  $HOME/.dotfiles/shell/bash_exports # Exports
  $HOME/.dotfiles/shell/bash_aliases # Aliases
  $HOME/.dotfiles/shell/functions/* # Functions
  $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
  $HOME/.dotfiles/shell/bash_paths # Path modifications
  #$(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
  #$HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
  )

  # if these files are readable, source them
  for index in ${!files[*]}
  do
    if [[ -r ${files[$index]} ]]; then
      source ${files[$index]}
    fi
  done
}

load_dotfiles
unset load_dotfiles

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Customize to your needs...

source $(brew --prefix nvm)/nvm.sh
nvm use iojs

. ~/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

[ -n "$TMUX" ]

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null;
done;

set -o vi
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Base16 Shell
BASE16_SHELL="$HOME/.dotfiles/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

#source ~/programming/emsdk_portable/emsdk_env.sh

