#!/bin/bash

# bash_config

# Make vim the default editor
export EDITOR="vim"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
# export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Export PhantomJS bin location (be explicit in case Homebrew is not installed
# in the default location)
export PHANTOMJS_BIN="$(brew --prefix)/bin/phantomjs"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"


# This is necessary because Ruby is stupid
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export CLOJURESCRIPT_HOME=~/programming/clojurescript
export GOPATH=$HOME/go
export GECKO_PATH=~/programming/mozilla-central

export JAVA_HOME=$(/usr/libexec/java_home)
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export CHICKEN_BUILD=~/programming/chicken-4.9.0.1
export NVM_DIR=~/.nvm

export GAIADIR="~/programming/gaia"
export NIGHTLY="/Applications/FirefoxNightly.app/Contents/MacOS"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";
# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:~/.cabal/bin:~/programming/android-sdk/platform-tools:~/programming/KindleGen_Mac_i386_v2_8:$CLOJURESCRIPT_HOME/bin:/Applications/Racket\ v6.1.1/bin:/usr/local/opt/go/libexec/bin:/usr/local/go/bin

